# CodeDeploy用の設定ファイル
version: 0.0
os: linux
files:
  - source: / # deploy対象
    destination: /home/ec2-user/ # deploy先のEC2のパス
hooks: # 同期的にscriptを実行
  ApplicationStop: # 初回のみ実行されない
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 30
      runas: ec2-user


