# CodeDeploy用の設定ファイル
version: 0.0
os: linux
files:
  - source: / # deploy対象
    destination: /home/ec2-user/comomon-api-server/ # deploy先のEC2のパス
permissions:
  - object: /home/ec2-user/
    owner: ec2-user
    mode: 744
hooks: # 同期的にscriptを実行
  ApplicationStop: # 初回は実行されない
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 30
      runas: ec2-user


