#!/bin/bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo "pwd"
pwd

echo "ls -a"
ls -a

echo "cd /home/ec2-user/aws-dev/"
cd /home/ec2-user/aws-dev/

echo "pm2 start dist/bin/www"
pm2 start dist/bin/www.js

