#!/bin/bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo "cd /home/ec2-user/comomon-api-server/"
cd /home/ec2-user/comomon-api-server/

echo "pm2 stop dist/bin/www || true"
pm2 stop dist/bin/www.js || true
